apiVersion: v1
kind: Service
metadata:
  {{- if .Values.web.service.annotations }}
  annotations:
    {{- tpl (toYaml .Values.web.service.annotations) . | nindent 4}}
  {{- end }}
  labels:
    app: {{ .Values.web.appName }}
    {{- include "search-api.labels" . | nindent 4 }}
  name: {{ include "search-api.web.fullname" . }}
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: {{ .Values.web.service.apiPort }}
      targetPort: {{ .Values.web.deployment.apiPort }}
  selector:
    app: {{ .Values.web.appName }}
  type: {{ .Values.web.service.type }}