{{- if ".Values.airflow-wrapper.enabled" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "search.fullname" . }}-airflow
  labels:
    app: airflow
    component: web
    release: {{ .Release.Name }}
  {{- if .Values.airflowWrapper.annotations }}
  annotations:
    {{ tpl (toYaml .Values.airflowWrapper.annotations) . | nindent 4}}
  {{- end }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: airflow
    component: web
    release: {{ .Release.Name }}
  type: ClusterIP
{{- end }}