apiVersion: v1
kind: Service
metadata:
  annotations:
  {{ tpl (toYaml .Values.service.annotations) . | nindent 4}}
  labels:
    app: {{ .Values.app_name }}
  name: {{ include "search-ui.fullname" . }}
spec:
  ports:
    - name: search-client-port
      protocol: TCP
      port: {{ .Values.http_port }}
      targetPort: {{ .Values.container_port }}
  selector:
    app: {{ .Values.app_name }}
  type: ClusterIP